export const projects = {
    carrinhoDeCompras: {
        title: 'Carrinho de E-commerce',
        project_url: 'https://marceloafl.github.io/carrinho-de-compras-ecommerce/',
        resume: 'Página simulando um carrinho de compras de e-commerce.',
        img_url: 'carrinho-de-ecommerce.png',
        languages: ['ReactJS', 'Typescript', 'CSS Modules, SCSS'],
        challenge: 'Em breve você vai poder conferir como foi o desafio de fazer este projeto.',
        resolution: 'Aqui você vai poder ver os detalhes de como este projeto foi construído',
    },
    calculadoraDePrecos: {
        title: 'Calculadora de Preços',
        project_url: 'https://marceloafl.github.io/calculadora-de-precos/',
        resume: 'Calcule o preço de venda de produtos e serviços',
        img_url: 'calculadora-de-precos.png',
        languages: ['HTML', 'CSS', 'Javascript'],
        challenge: 'Em breve você vai poder conferir como foi o desafio de fazer este projeto.',
        resolution: 'Aqui você vai poder ver os detalhes de como este projeto foi construído',
    },
    jogoDaMemoria: {
        title: 'Jogo da Memória',
        project_url: 'https://marceloafl.github.io/jogo-da-memoria/',
        resume: 'Jogo da memória com três níveis de dificuldade',
        img_url: 'jogo-da-memoria.png',
        languages: ['HTML', 'CSS', 'Javascript'],
        challenge: 'Em breve você vai poder conferir como foi o desafio de fazer este projeto.',
        resolution: 'Aqui você vai poder ver os detalhes de como este projeto foi construído',
    },
    lojaOnline: {
        title: 'Loja On-line',
        project_url: 'https://marceloafl.github.io/e-commerce/',
        resume: 'Página inicial de e-commerce responsivo',
        img_url: 'loja-online.png',
        languages: ['HTML', 'CSS'],
        challenge: 'Em breve você vai poder conferir como foi o desafio de fazer este projeto.',
        resolution: 'Aqui você vai poder ver os detalhes de como este projeto foi construído',
    },
    cloneflix: {
        title: 'Cloneflix',
        project_url: 'https://marceloafl.github.io/cloneflix/',
        resume: 'Clone da Netflix',
        img_url: 'cloneflix.png',
        languages: ['HTML', 'CSS', 'Javascript'],
        challenge: 'Em breve você vai poder conferir como foi o desafio de fazer este projeto.',
        resolution: 'Aqui você vai poder ver os detalhes de como este projeto foi construído',
    },
    listaDeCompras: {
        title: 'Lista de Compras',
        project_url: 'https://marceloafl.github.io/lista-de-compras/',
        resume: 'Organize sua lista durante as compras, adicionando, riscando e excluindo itens.',
        img_url: 'lista-de-compras.png',
        languages: ['HTML', 'CSS'],
        challenge: 'Em breve você vai poder conferir as como foi o desafio de fazer este projeto.',
        resolution: 'Aqui você vai poder ver os detalhes de como este projeto foi construído',
    },
    portfolio: {
        title: 'Portfólio',
        project_url: 'https://marceloafl.github.io/portfolio/',
        resume: 'Meu site com portfólio de projetos e informações sobre meu trabalho.',
        img_url: 'portfolio.png',
        languages: ['HTML', 'CSS', 'Javascript'],
        challenge: 'Em breve você vai poder conferir como foi o desafio de fazer este projeto.',
        resolution: 'Aqui você vai poder ver os detalhes de como este projeto foi construído',
    },
    buscaCep: {
        title: 'Busca CEP',
        project_url: 'https://marceloafl.github.io/busca-cep/',
        resume: 'Simulação de formulário para cadastro de endereço com consumo de API para buscar CEP.',
        img_url: 'busca-cep.png',
        languages: ['HTML', 'CSS', 'Javascript'],
        challenge: 'Em breve você vai poder conferir como foi o desafio de fazer este projeto.',
        resolution: 'Aqui você vai poder ver os detalhes de como este projeto foi construído',
    },
};

